apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-creator
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-federated-auth-reader-token-creator
subjects:
- kind: ServiceAccount
  name: kube-federated-auth-reader
roleRef:
  kind: Role
  name: token-creator
  apiGroup: rbac.authorization.k8s.io
