apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-federated-auth
  namespace: kube-federated-auth
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-federated-auth
  namespace: kube-federated-auth
subjects:
- kind: ServiceAccount
  name: kube-federated-auth
  namespace: kube-federated-auth
roleRef:
  kind: Role
  name: kube-federated-auth
  apiGroup: rbac.authorization.k8s.io
