{{- if eq (toString .Values.cluster_b.create_secret) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: multi-k8s-auth
type: Opaque
data:
  cluster-b-token: {{ .Values.cluster_b.bootstrap_token }}
  cluster-b-ca.crt: {{ .Values.cluster_b.ca_cert }}
{{- end }}
