apiVersion: v1
kind: Service
metadata:
  name: kube-federated-auth
  namespace: kube-federated-auth
spec:
  type: NodePort
  selector:
    app: kube-federated-auth
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080
